
[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 10.0
## Macos
# size = 13.0
# size = 18.0

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 0 }

[general]
import = ["~/.config/alacritty/themes/themes/tokyo-night-storm.toml"]
# opacity = 0.80
# blur = true
